name: license_prep_app
description: USA License Prep App - A subscription-based license preparation application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/signs/
    - assets/images/signs/examples/
    - assets/images/traffic_lights/
    - assets/images/quiz/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
